# Generated by Django 3.2.6 on 2021-11-30 05:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=65)),
                ('country', models.CharField(max_length=65)),
                ('city', models.CharField(max_length=65)),
                ('salary', models.FloatField()),
            ],
        ),
    ]
